export const DAIRY_INGREDIENTS = [
  "milk",
  "whole milk",
  "skim milk",
  "low-fat milk",
  "2% milk",
  "1% milk",
  "fat-free milk",
  "buttermilk",
  "powdered milk",
  "evaporated milk",
  "condensed milk",
  "lactose-free milk",
  "almond milk",
  "soy milk",
  "oat milk",
  "coconut milk",
  "heavy cream",
  "whipping cream",
  "half and half",
  "light cream",
  "yogurt",
  "greek yogurt",
  "plain yogurt",
  "flavored yogurt",
  "low-fat yogurt",
  "non-fat yogurt",
  "frozen yogurt",
  "drinkable yogurt",
  "kefir",
  "butter",
  "salted butter",
  "unsalted butter",
  "clarified butter",
  "ghee",
  "margarine",
  "cheese",
  "cheddar cheese",
  "mozzarella cheese",
  "parmesan cheese",
  "swiss cheese",
  "blue cheese",
  "feta cheese",
  "gouda",
  "brie",
  "camembert",
  "provolone",
  "colby jack",
  "pepper jack",
  "monterey jack",
  "ricotta cheese",
  "cottage cheese",
  "cream cheese",
  "neufchâtel cheese",
  "queso fresco",
  "queso blanco",
  "paneer",
  "halloumi",
  "goat cheese",
  "havarti",
  "asiago",
  "gruyère",
  "pecorino romano",
  "fontina",
  "mascarpone",
  "roquefort",
  "muenster",
  "string cheese",
  "cheese curds",
  "processed cheese",
  "american cheese",
  "vegan cheese",
  "sour cream",
  "light sour cream",
  "fat-free sour cream",
  "crème fraîche",
  "clotted cream",
  "custard",
  "pudding",
  "flan",
  "whey",
  "casein",
  "ice cream",
  "gelato",
  "sherbet",
  "soft serve",
  "milkshake",
  "malts",
  "cream-based sauces",
  "cheese sauce",
  "ranch dressing",
  "caesar dressing",
  "alfredo sauce",
  "bechamel sauce",
  "cheese dip",
  "queso dip",
  "coffee creamer",
  "flavored coffee creamer",
  "powdered coffee creamer",
  "protein shakes",
  "whey protein powder",
  "casein protein powder",
];

export const FRESH_PRODUCT_INGREDIENTS = [
  "apple",
  "apricot",
  "artichoke",
  "arugula",
  "asparagus",
  "avocado",
  "banana",
  "beet",
  "bell pepper",
  "blackberry",
  "blueberry",
  "bok choy",
  "broccoli",
  "brussels sprouts",
  "butternut squash",
  "cabbage",
  "cantaloupe",
  "carrot",
  "cauliflower",
  "celery",
  "cherry",
  "cherry tomato",
  "chili pepper",
  "clementine",
  "coconut",
  "collard greens",
  "corn",
  "cranberry",
  "cucumber",
  "daikon",
  "date",
  "delicata squash",
  "dragon fruit",
  "durian",
  "eggplant",
  "elderberry",
  "endive",
  "fig",
  "fennel",
  "garlic",
  "ginger",
  "grape",
  "grapefruit",
  "green bean",
  "green onion",
  "guava",
  "honeydew melon",
  "jalapeño",
  "jicama",
  "kale",
  "kiwi",
  "kohlrabi",
  "leek",
  "lemon",
  "lettuce",
  "lime",
  "longan",
  "loquat",
  "lychee",
  "mango",
  "mandarin",
  "mulberry",
  "mushroom",
  "mustard greens",
  "nectarine",
  "okra",
  "olive",
  "onion",
  "orange",
  "papaya",
  "passion fruit",
  "peach",
  "pear",
  "peas",
  "persimmon",
  "pineapple",
  "plantain",
  "plum",
  "pomegranate",
  "pomelo",
  "potato",
  "pumpkin",
  "quince",
  "radicchio",
  "radish",
  "rambutan",
  "raspberry",
  "red onion",
  "red pepper",
  "rhubarb",
  "romaine",
  "rutabaga",
  "scallion",
  "shallot",
  "snow pea",
  "spinach",
  "sprouts",
  "starfruit",
  "strawberry",
  "summer squash",
  "sweet corn",
  "sweet pepper",
  "sweet potato",
  "swiss chard",
  "tamarillo",
  "tamarind",
  "tangelo",
  "tangerine",
  "tomatillo",
  "tomato",
  "turnip",
  "watercress",
  "watermelon",
  "white onion",
  "yellow onion",
  "yellow squash",
  "yam",
  "zucchini",
  "acorn squash",
  "alfalfa sprouts",
  "banana pepper",
  "beet greens",
  "bitter melon",
  "broccolini",
  "butter lettuce",
  "carambola",
  "chayote",
  "chicory",
  "chinese cabbage",
  "choy sum",
  "cilantro",
  "clementine",
  "cress",
  "curry leaf",
  "dandelion greens",
  "dragonfruit",
  "edamame",
  "epazote",
  "escarole",
  "fiddlehead",
  "garbanzo beans",
  "golden beet",
  "golden kiwi",
  "gourd",
  "grape tomato",
  "green chile",
  "green garlic",
  "green pea",
  "hearts of palm",
  "horseradish",
  "iceberg lettuce",
  "italian parsley",
  "jerusalem artichoke",
  "juniper berry",
  "kabocha squash",
  "kamote tops",
  "kiwano",
  "lacinato kale",
  "lamb's lettuce",
  "lemon balm",
  "lemongrass",
  "lotus root",
  "mangosteen",
  "marionberry",
  "mizuna",
  "moringa",
  "muscadine grape",
  "napa cabbage",
  "nopales",
  "oregano",
  "parsley",
  "parsnip",
  "pigeon pea",
  "purple cabbage",
  "purple sweet potato",
  "radish greens",
  "rainbow chard",
  "rapini",
  "red chard",
  "red kuri squash",
  "rosemary",
  "sage",
  "savoy cabbage",
  "seaweed",
  "sorrel",
  "sunchoke",
  "taro",
  "tatsoi",
  "thai basil",
  "thai chili",
  "thyme",
  "tree tomato",
  "turmeric",
  "wasabi",
  "wax bean",
  "white radish",
  "winged bean",
  "yuca",
  "yucca root",
];

export const BAKING_INGREDIENTS = [
  "flour",
  "all-purpose flour",
  "almond flour",
  "baking powder",
  "baking soda",
  "brown sugar",
  "butter",
  "buttermilk",
  "cake flour",
  "cane sugar",
  "cocoa powder",
  "cornstarch",
  "cornmeal",
  "coconut flour",
  "corn syrup",
  "cream of tartar",
  "dark chocolate",
  "dry yeast",
  "egg",
  "egg yolk",
  "egg white",
  "flaxseed meal",
  "gluten",
  "granulated sugar",
  "honey",
  "maple syrup",
  "margarine",
  "molasses",
  "muffin mix",
  "oats",
  "peanut butter",
  "powdered sugar",
  "preserves",
  "raisins",
  "rice flour",
  "salt",
  "semi-sweet chocolate chips",
  "shortening",
  "sifted flour",
  "sour cream",
  "sprinkles",
  "sweetened condensed milk",
  "vanilla extract",
  "vinegar",
  "walnuts",
  "whole wheat flour",
  "white chocolate",
  "yeast",
  "baking chocolate",
  "brownie mix",
  "buttermilk powder",
  "carob powder",
  "chocolate chips",
  "chocolate syrup",
  "cinnamon",
  "cloves",
  "confectioner's sugar",
  "cream cheese",
  "custard powder",
  "decorating sugar",
  "dried fruit",
  "egg replacer",
  "instant pudding mix",
  "lemon zest",
  "maple sugar",
  "malted milk powder",
  "marzipan",
  "nutmeg",
  "orange zest",
  "peach preserves",
  "pearl sugar",
  "pears",
  "pie crust mix",
  "pie filling",
  "popcorn",
  "pumpkin puree",
  "pumpkin spice",
  "pudding mix",
  "raisins",
  "refrigerated dough",
  "ripe bananas",
  "shredded coconut",
  "silken tofu",
  "sugar cubes",
  "tapioca flour",
  "toffee bits",
  "unsweetened applesauce",
  "unsweetened cocoa",
  "unsweetened chocolate",
  "vanilla bean paste",
  "vanilla pudding",
  "vegetable oil",
  "wheat germ",
  "white cornmeal",
  "white vinegar",
  "whole milk",
  "yogurt",
];

export const MEAT_AND_POULTRY_INGREDIENTS = [
  "bacon",
  "beef",
  "beef brisket",
  "beef chuck",
  "beef flank",
  "beef liver",
  "beef ribs",
  "beef round",
  "beef stew meat",
  "beef tenderloin",
  "beef tongue",
  "beef tri-tip",
  "bison",
  "boar",
  "bone marrow",
  "bratwurst",
  "buffalo",
  "canned ham",
  "canned tuna",
  "chicken",
  "chicken breast",
  "chicken drumsticks",
  "chicken thighs",
  "chicken wings",
  "chicken liver",
  "chicken sausage",
  "chorizo",
  "clam",
  "corned beef",
  "crab",
  "duck",
  "duck breast",
  "duck leg",
  "elk",
  "fish fillets",
  "flounder",
  "foie gras",
  "goat",
  "goat chops",
  "goat meat",
  "goat ribs",
  "goose",
  "ground beef",
  "ground lamb",
  "ground pork",
  "ground turkey",
  "ham",
  "ham hocks",
  "hot dog",
  "italian sausage",
  "jerky",
  "kangaroo",
  "kielbasa",
  "lamb",
  "lamb chops",
  "lamb leg",
  "lamb rack",
  "lamb ribs",
  "lamb shoulder",
  "lamb stew meat",
  "lamb tongue",
  "liverwurst",
  "lobster",
  "mackerel",
  "meatballs",
  "mussels",
  "octopus",
  "ostrich",
  "oysters",
  "pork",
  "pork belly",
  "pork chops",
  "pork hocks",
  "pork ribs",
  "pork sausage",
  "pork shoulder",
  "pork tenderloin",
  "pork tongue",
  "rabbit",
  "rack of lamb",
  "reindeer",
  "salmon",
  "scallops",
  "shrimp",
  "sirloin",
  "squid",
  "steak",
  "steak tips",
  "swordfish",
  "t-bone steak",
  "tilapia",
  "turkey",
  "turkey breast",
  "turkey leg",
  "turkey neck",
  "veal",
  "veal chops",
  "veal liver",
  "veal ribs",
  "veal stew meat",
  "venison",
  "wiener",
  "zebu",
  "antelope",
  "andouille sausage",
  "apple sausage",
  "armadillo",
  "barbecue ribs",
  "beef bacon",
  "beef sausages",
  "beef tongue",
  "beef heart",
  "beef liver",
  "beef spare ribs",
  "beef stew",
  "beef striploin",
  "beef Wellington",
  "black pudding",
  "blue crab",
  "braised pork",
  "braised lamb",
  "braised veal",
  "brisket",
  "buffalo ribs",
  "calf's liver",
  "canned chili",
  "canned sausage",
  "canned turkey",
  "canned chicken",
  "caribou",
  "caviar",
  "chicken gizzards",
  "chicken nuggets",
  "chicken patties",
  "chicken salad",
  "chicken wings",
  "clam chowder",
  "clams",
  "clove ham",
  "cornish hen",
  "crab cakes",
  "crawfish",
  "cubed steak",
  "dried meat",
  "duck confit",
  "duck legs",
  "duck thighs",
  "duck wings",
  "duckling",
  "duck sausage",
  "eel",
  "english sausage",
  "fish cakes",
  "flank steak",
  "frozen meatballs",
  "game meat",
  "goat stew",
  "goose liver",
  "grilled chicken",
  "grilled pork",
  "grilled steak",
  "grilled venison",
  "guinea fowl",
  "ham steak",
  "hamstring",
  "hot links",
  "hushpuppies",
  "italian sausage links",
  "jerky beef",
  "jerky chicken",
  "jerky pork",
  "jerky turkey",
  "kebabs",
  "lamb stew",
  "lamb neck",
  "lamb shoulder",
  "lamb sausages",
  "lamb shank",
  "lamb steaks",
  "lemon pepper chicken",
  "lobster tail",
  "longaniza sausage",
  "minced lamb",
  "minced pork",
  "minced turkey",
  "moose",
  "mutton",
  "nugget chicken",
  "oysters on the half shell",
  "paddlefish",
  "pate",
  "pork sausage links",
  "pork sausage patties",
  "pork schnitzel",
  "pork spare ribs",
  "pork tenderloin",
  "prawn",
  "prime rib",
  "rack of lamb",
  "roast chicken",
  "roast pork",
  "roast turkey",
  "roast veal",
  "rockfish",
  "salmon fillet",
  "schnitzel",
  "shrimp scampi",
  "smoked pork",
  "smoked turkey",
  "smoked sausage",
  "smoked salmon",
  "smoked trout",
  "soft shell crab",
  "steak strips",
  "steak wrap",
  "stewed lamb",
  "stewed pork",
  "stewed venison",
  "stuffed chicken",
  "stuffed turkey",
  "swordfish steak",
  "t-bone",
  "tail-on shrimp",
  "tenderloin",
  "tomahawk steak",
  "turkey bacon",
  "turkey cutlets",
  "turkey sausage",
  "veal shanks",
  "veal tongue",
  "veal cutlets",
  "veal stew",
  "venison steaks",
  "venison sausage",
  "venison chops",
  "wild boar",
  "wild rabbit",
  "yellowtail",
  "zander",
];

export const SPICES_AND_SEASONINGS_INGREDIENTS = [
  "allspice",
  "anise",
  "apple pie spice",
  "asafoetida",
  "basil",
  "bay leaf",
  "black pepper",
  "caraway",
  "cardamom",
  "cayenne pepper",
  "celery salt",
  "chili flakes",
  "chili powder",
  "chili sauce",
  "chili seasoning",
  "chinese five spice",
  "cinnamon",
  "cloves",
  "coriander",
  "cumin",
  "curry powder",
  "dill",
  "dried garlic",
  "dried onion",
  "fennel",
  "garam masala",
  "garlic powder",
  "garlic salt",
  "ginger",
  "herbes de provence",
  "honey powder",
  "italian seasoning",
  "jasmine rice seasoning",
  "juniper berries",
  "kalamata olives",
  "ketchup powder",
  "kitchen bouquet",
  "lemon pepper",
  "lime zest",
  "mace",
  "marjoram",
  "mustard powder",
  "nutmeg",
  "onion powder",
  "oregano",
  "paprika",
  "parsley",
  "peanut powder",
  "peruvian spice blend",
  "poppy seeds",
  "rosemary",
  "saffron",
  "sage",
  "salt",
  "sea salt",
  "sesame seeds",
  "smoked paprika",
  "sweet paprika",
  "tandoori spice",
  "tarragon",
  "thai basil",
  "thyme",
  "turmeric",
  "wasabi powder",
  "za'atar",
  "adobo seasoning",
  "aji amarillo",
  "all-purpose seasoning",
  "amchur",
  "arbol chili",
  "asafoetida powder",
  "barbecue seasoning",
  "berbere",
  "black mustard seeds",
  "black salt",
  "brazilian seasoning",
  "cajun seasoning",
  "cajun spice",
  "caramelized onion powder",
  "chili garlic sauce",
  "chili paste",
  "chinese mustard",
  "chili oil",
  "chili pepper flakes",
  "chili seasoning mix",
  "chili salt",
  "chile de arbol",
  "chili powder mix",
  "cinnamon sugar",
  "clove powder",
  "coriander seeds",
  "curry leaves",
  "curry paste",
  "dry mustard",
  "duck seasoning",
  "fajita seasoning",
  "fish sauce",
  "french seasoning",
  "garlic chili paste",
  "garlic flakes",
  "garlic herb",
  "ginger powder",
  "green chili powder",
  "harissa",
  "hot pepper flakes",
  "italian parsley",
  "jalapeno powder",
  "jerk seasoning",
  "lemon zest powder",
  "lime powder",
  "low sodium salt",
  "marinade seasoning",
  "mexican oregano",
  "mojo seasoning",
  "mole",
  "mustard seeds",
  "oregano leaf",
  "paprika blend",
  "peppercorns",
  "peppermint",
  "poultry seasoning",
  "rosemary seasoning",
  "safflower",
  "sichuan pepper",
  "smoked salt",
  "sour salt",
  "spicy seasoning",
  "spicy salt",
  "spicy vinegar",
  "steak seasoning",
  "taco seasoning",
  "thai chili",
  "togarashi",
  "turmeric powder",
  "vegan seasoning",
  "vegetable seasoning",
  "white pepper",
  "cayenne",
  "fennel seed",
  "ground coriander",
  "tamarind powder",
  "tempeh seasoning",
  "vietnamese seasoning",
  "vegan chicken spice",
  "sriracha seasoning",
  "seaweed flakes",
  "spice mix",
  "spicy chili sauce",
  "salad seasoning",
  "black cumin",
  "white cumin",
  "wild thyme",
  "yogurt seasoning",
  "yellow curry powder",
  "yellow mustard",
  "ras el hanout",
  "italian herbs",
  "chili lime",
  "peanut seasoning",
  "cinnamon stick",
  "ginger slices",
  "juniper seasoning",
  "lime seasoning",
  "chili powder blend",
  "onion salt",
  "garlic blend",
  "curry seasoning",
  "szechuan pepper",
  "wasabi paste",
  "tahini spice",
  "balsamic seasoning",
  "turmeric blend",
  "chili lime seasoning",
  "gravy seasoning",
  "dried oregano",
  "smoked chili powder",
  "rosemary oil",
  "jalapeno salt",
  "tamarind paste",
  "seaweed seasoning",
  "vinegar powder",
  "green curry seasoning",
  "chili bbq seasoning",
  "ginger root",
  "rosemary oil seasoning",
  "chili lemon salt",
  "lemon zest seasoning",
  "spicy garlic seasoning",
  "salt blend",
  "tomato powder",
  "garlic chili seasoning",
  "miso seasoning",
  "pasta seasoning",
  "caramelized garlic",
  "red chili powder",
  "paprika seasoning",
  "honey mustard",
  "tandoori seasoning",
  "poultry rub",
  "garlic olive oil",
  "grill seasoning",
  "potato seasoning",
  "spicy brown mustard",
  "mustard powder mix",
  "garlic chili oil",
  "white mustard",
  "blackened seasoning",
  "peach seasoning",
  "savory herb seasoning",
  "chili curry",
  "pineapple seasoning",
  "herb seasoning",
  "sweet curry",
  "dried chili",
  "harissa paste",
  "turmeric salt",
  "cajun rub",
  "cinnamon powder",
  "dried rosemary",
  "ginger chili sauce",
  "onion spice",
  "oregano flakes",
  "chili rub",
  "baking spice",
];

export const SAUCES_AND_CONDIMENT_INGREDIENTS = [
  "barbecue sauce",
  "balsamic vinegar",
  "bean paste",
  "buffalo sauce",
  "cheese sauce",
  "chili sauce",
  "chocolate sauce",
  "cider vinegar",
  "cocktail sauce",
  "cream cheese",
  "fish sauce",
  "flour sauce",
  "garlic butter",
  "greek yogurt",
  "hoisin sauce",
  "hot sauce",
  "honey mustard",
  "hot wing sauce",
  "hummus",
  "ketchup",
  "kimchi",
  "korean barbecue sauce",
  "lemon juice",
  "mayo",
  "mustard",
  "olive oil",
  "oregano oil",
  "pesto",
  "plum sauce",
  "salad dressing",
  "salsa",
  "sriracha",
  "soy sauce",
  "steak sauce",
  "sweet and sour sauce",
  "tartar sauce",
  "teriyaki sauce",
  "vinegar",
  "wasabi",
  "white vinegar",
  "worcestershire sauce",
  "aioli",
  "almond butter",
  "apple cider vinegar",
  "artichoke dip",
  "avocado sauce",
  "bacon aioli",
  "balsamic glaze",
  "banana ketchup",
  "barbecue glaze",
  "beurre blanc",
  "black bean sauce",
  "blue cheese dressing",
  "bologna mustard",
  "bordeaux sauce",
  "buffalo wing sauce",
  "buttermilk dressing",
  "caramel sauce",
  "carrot sauce",
  "caesar dressing",
  "cajun sauce",
  "calamata olive dip",
  "caribbean jerk sauce",
  "cheese fondue",
  "chermoula",
  "chili garlic sauce",
  "chili oil",
  "chinese mustard",
  "chocolate syrup",
  "cilantro chutney",
  "coconut milk",
  "coconut sauce",
  "creole mustard",
  "cucumber sauce",
  "dijon mustard",
  "french dressing",
  "french onion dip",
  "garlic aioli",
  "garlic sauce",
  "ginger sauce",
  "greek dressing",
  "green goddess dressing",
  "honey sauce",
  "hot chili paste",
  "hot garlic sauce",
  "hot mustard",
  "hummus dressing",
  "jalapeno sauce",
  "jalapeno vinegar",
  "japanese soy sauce",
  "katsu sauce",
  "korean hot sauce",
  "lemon dressing",
  "lemon pepper sauce",
  "mango chutney",
  "maple syrup",
  "mayonnaise",
  "meatball sauce",
  "miso paste",
  "mustard vinaigrette",
  "nando's sauce",
  "oil and vinegar",
  "olive tapenade",
  "onion jam",
  "orange sauce",
  "oregano dressing",
  "paprika sauce",
  "peach chutney",
  "peanut sauce",
  "pepper jelly",
  "pepperoncini",
  "pineapple salsa",
  "poppy seed dressing",
  "pomegranate molasses",
  "pork sauce",
  "prego spaghetti sauce",
  "ranch dressing",
  "relish",
  "sambal oelek",
  "sauce vierge",
  "sesame oil",
  "shoyu sauce",
  "spicy ketchup",
  "spicy mayo",
  "spicy mustard",
  "spinach dip",
  "sweet chili sauce",
  "sweet mustard",
  "tomato sauce",
  "tomato paste",
  "tomato puree",
  "truffle oil",
  "tartar sauce",
  "teriyaki glaze",
  "thai peanut sauce",
  "tuscan seasoning sauce",
  "tzatziki",
  "vegan mayo",
  "vegetable oil",
  "vinegar sauce",
  "yellow mustard",
  "zesty sauce",
  "cajun aioli",
  "chili paste",
  "chinese five spice sauce",
  "cilantro lime dressing",
  "coconut chutney",
  "creamy garlic dressing",
  "creole sauce",
  "cucumber relish",
  "dried garlic sauce",
  "dried mushroom sauce",
  "dressing",
  "eggplant dip",
  "enchilada sauce",
  "fig balsamic glaze",
  "fish taco sauce",
  "garlic pepper sauce",
  "green curry paste",
  "green curry sauce",
  "green chili sauce",
  "greek tzatziki",
  "hot pepper relish",
  "honey glaze",
  "hot barbecue sauce",
  "huevos rancheros sauce",
  "italian dressing",
  "italian pesto",
  "jerk barbecue sauce",
  "jalapeno hot sauce",
  "korean hot chili paste",
  "lime salsa",
  "lime wedge sauce",
  "mango sauce",
  "mustard sauce",
  "olive tapenade",
  "onion dip",
  "paprika aioli",
  "passata",
  "pasta sauce",
  "peach glaze",
  "pesto dressing",
  "pineapple mustard",
  "pomegranate sauce",
  "quinoa dressing",
  "roasted garlic dressing",
  "roasted pepper sauce",
  "saffron oil",
  "salsa verde",
  "sambal",
  "sesame paste",
  "smoked mustard",
  "spicy tahini",
  "spicy yogurt",
  "sweet hot mustard",
  "sweet onion dressing",
  "tandoori sauce",
  "tomato ketchup",
  "tomato salad dressing",
  "tropical fruit sauce",
  "truffle mayonnaise",
  "turmeric sauce",
  "wasabi dressing",
  "whiskey glaze",
  "yellow chili sauce",
  "yellow curry paste",
  "zatar sauce",
  "zingy mustard",
  "zucchini sauce",
  "apricot glaze",
  "bacon jam",
  "balsamic vinaigrette",
  "barbecue rub",
  "bbq marinade",
  "black bean salsa",
  "butter sauce",
  "caramelized onion sauce",
  "carrot ginger sauce",
  "cherry barbecue sauce",
  "chicken sauce",
  "chili vinaigrette",
  "chipotle sauce",
  "coconut curry",
  "crab sauce",
  "cranberry sauce",
  "dijon aioli",
  "eggplant sauce",
  "fennel mustard sauce",
  "fish broth",
  "garlic butter sauce",
  "gravy",
  "green chili salsa",
  "habanero sauce",
  "honey barbecue",
  "lemon aioli",
  "mango salsa",
  "marinara sauce",
  "orange glaze",
  "paprika mayo",
  "peanut butter sauce",
  "peppercorn sauce",
  "pistachio sauce",
  "pumpkin spice sauce",
  "spicy hot sauce",
  "sriracha mayo",
  "sweet basil sauce",
  "tamarind chutney",
  "tartar aioli",
  "tomato garlic sauce",
  "tomato salsa",
  "yogurt dip",
  "yellow chili paste",
];

export const OILS_AND_FATS_INGREDIENTS = [
  "avocado oil",
  "butter",
  "canola oil",
  "coconut oil",
  "corn oil",
  "duck fat",
  "grapeseed oil",
  "lard",
  "olive oil",
  "peanut oil",
  "sesame oil",
  "sunflower oil",
  "vegetable oil",
  "walnut oil",
  "almond oil",
  "palm oil",
  "ghee",
  "safflower oil",
  "rice bran oil",
  "truffle oil",
  "hazelnut oil",
  "mustard oil",
  "soybean oil",
  "chicken fat",
  "beef tallow",
  "bacon fat",
  "cocoa butter",
  "clarified butter",
  "cream",
  "margarine",
  "shortening",
  "sesame seed oil",
  "pumpkin seed oil",
  "flaxseed oil",
  "hemp oil",
  "grape seed oil",
  "tallow",
  "shea butter",
  "poppyseed oil",
  "cherry oil",
  "perilla oil",
  "peanut butter",
  "olive pomace oil",
  "coconut butter",
  "lard fat",
  "avocado butter",
  "almond butter",
  "sunflower seed oil",
  "coconut milk",
  "cashew butter",
  "soybean oil",
  "cornstarch",
  "milk fat",
  "buttermilk",
  "sour cream",
  "shea oil",
  "cacao butter",
  "moringa oil",
  "turmeric oil",
  "pumpkin oil",
  "black seed oil",
  "peppermint oil",
  "ginger oil",
  "fish oil",
  "anchovy oil",
  "cod liver oil",
  "rosemary oil",
  "eucalyptus oil",
  "chili oil",
  "sesame seed paste",
  "mustard seed oil",
  "avocado seed oil",
  "curry leaf oil",
  "palm kernel oil",
  "baobab oil",
  "cacao butter oil",
  "coconut flour",
  "tamarind oil",
  "yogurt butter",
  "whipped cream",
  "ricotta cheese",
  "lactose free butter",
  "clarified ghee",
  "maple butter",
  "cornmeal",
  "bacon drippings",
  "butter flavored oil",
  "cocoa butter paste",
  "kiwi seed oil",
  "safflower butter",
  "chocolate hazelnut spread",
  "coconut ghee",
  "walnut butter",
  "sundried tomato oil",
  "blue cheese butter",
  "pecan oil",
  "pistachio oil",
  "macadamia nut oil",
  "brazil nut oil",
];

export const GRAINS_AND_BREADS_INGREDIENTS = [
  "white bread",
  "whole wheat bread",
  "sourdough",
  "rye bread",
  "multigrain bread",
  "baguette",
  "ciabatta",
  "brioche",
  "english muffin",
  "pita bread",
  "naan",
  "tortilla",
  "flatbread",
  "cornbread",
  "focaccia",
  "croutons",
  "breadsticks",
  "gluten-free bread",
  "oat bread",
  "zucchini bread",
  "banana bread",
  "pizza dough",
  "pumpernickel bread",
  "bagels",
  "croissant",
  "pretzel",
  "hoagie roll",
  "sub roll",
  "buns",
  "sweet rolls",
  "whole grain bread",
  "white sandwich bread",
  "whole wheat sandwich bread",
  "rye sandwich bread",
  "english muffin bread",
  "bread crumbs",
  "bread flour",
  "rice flour",
  "cornmeal",
  "oats",
  "quinoa",
  "farro",
  "barley",
  "buckwheat",
  "bulgur",
  "couscous",
  "spelt",
  "teff",
  "amaranth",
  "millet",
  "kamut",
  "sorghum",
  "rice",
  "wild rice",
  "brown rice",
  "white rice",
  "black rice",
  "jasmine rice",
  "basmati rice",
  "arborio rice",
  "carnaroli rice",
  "polenta",
  "tapioca",
  "semolina",
  "polenta flour",
  "farina",
  "grits",
  "rice noodles",
  "pasta",
  "macaroni",
  "penne",
  "spaghetti",
  "fettuccine",
  "lasagna noodles",
  "rotini",
  "farfalle",
  "rigatoni",
  "orzo",
  "baked beans",
  "soba noodles",
  "udon noodles",
  "ramen",
  "egg noodles",
  "gnocchi",
  "cavatappi",
  "pasta shells",
  "gluten-free pasta",
  "corn tortillas",
  "flour tortillas",
  "taco shells",
  "tamales",
  "rice cakes",
  "crackers",
  "oatmeal",
  "instant oatmeal",
  "steel-cut oats",
  "rolled oats",
  "grape nuts",
  "muesli",
  "granola",
  "bran flakes",
  "cornflakes",
  "rice puffs",
  "puffed quinoa",
  "puffed rice",
  "barley flakes",
  "rye flakes",
  "spelt flakes",
  "quinoa flakes",
  "chia seeds",
  "flax seeds",
  "hemp seeds",
  "pumpkin seeds",
  "sunflower seeds",
  "couscous flour",
  "farro flour",
  "teff flour",
  "sorghum flour",
  "amaranth flour",
  "kamut flour",
  "spelt flour",
  "rice bran",
  "rice pudding",
  "basmati noodles",
  "egg-free pasta",
  "organic pasta",
  "instant rice",
  "brown rice noodles",
  "polenta sticks",
  "arborio rice pudding",
  "sticky rice",
  "flour tortillas",
  "corn tortillas",
  "tapioca flour",
  "cabbage rolls",
  "quinoa pasta",
  "gravy mix",
  "tapioca pearls",
  "buckwheat flour",
  "pasta sheets",
  "gluten-free pizza dough",
  "chickpea pasta",
  "black bean pasta",
  "rice noodles stir fry",
  "soba noodles stir fry",
  "kasha",
  "chickpea flour",
  "flour tortilla chips",
  "whole grain tortillas",
  "herb flatbread",
  "dried beans",
  "dried lentils",
  "butter biscuits",
  "poppy seed bread",
  "sesame seed bread",
  "onion rolls",
  "rye rolls",
  "whole wheat rolls",
  "corn muffins",
  "popovers",
  "almond flour bread",
  "quinoa bread",
  "potato bread",
  "gluten-free rolls",
  "sunflower seed bread",
  "molasses bread",
  "scone",
  "cheese bread",
  "cinnamon swirl bread",
  "sourdough rolls",
  "bread pudding",
  "date nut bread",
  "lavash",
  "flatbreads",
  "carrot cake",
  "barmbrack",
  "pumpkin bread",
  "kiwi bread",
  "fruitcake",
  "blueberry muffins",
  "apricot bread",
  "sweet potato bread",
  "caramel bread",
  "chocolate chip bread",
  "kiwi muffins",
  "corn tortillas chips",
  "soft taco shells",
  "onion flatbread",
  "garlic naan",
  "herbed breadsticks",
  "salted butter rolls",
  "apple cinnamon bread",
  "sourdough crackers",
  "toasted bread crumbs",
  "baguette sticks",
  "potato rolls",
  "biscuits",
  "multigrain pita",
  "gluten-free pita",
  "spelt bread",
  "tapioca rolls",
  "polenta bread",
  "caraway seed bread",
  "rye crackers",
  "cornbread muffins",
  "sweet bread rolls",
  "herbed focaccia",
  "sweet wheat bread",
  "cheddar bread",
  "italian bread",
  "whole grain pizza dough",
  "pretzel rolls",
  "chia bread",
  "chocolate bread",
  "tomato bread",
  "onion flat bread",
  "breaded chicken crumbs",
  "pizza crust mix",
  "taco bread",
  "vegan tortilla",
  "herbed pizza dough",
  "whole wheat pita",
  "quinoa muffins",
  "flour sandwich bread",
  "plain flour bread",
  "homemade flatbread",
  "spinach bread",
  "brioche buns",
  "flat bread pizza",
  "pita chips",
  "buttermilk bread",
  "spicy cornbread",
  "garlic bread sticks",
  "rice pilaf",
  "buckwheat pancakes",
  "germinated rice",
  "pita sandwich",
  "blue corn tortillas",
  "rice cakes snack",
  "baguette slices",
  "pasta salad",
  "garlic naan bread",
  "cabbage bread",
  "sunflower bread",
  "whole wheat pasta",
  "corn flour bread",
  "banana oat bread",
  "lentil bread",
  "rice flour pizza crust",
  "brie bread",
  "tortilla wraps",
  "butterfly bread",
  "gluten-free pasta shells",
  "mini breadsticks",
  "cheddar cheese bread",
  "avocado toast bread",
  "poppy seed rolls",
  "maple oat bread",
  "buttermilk rolls",
];
